on:
  pull_request:
    types:
      - opened
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output context
        run: echo "The context is ${{ toJSON(github.event) }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Deployed!"
