name: Reusable Deploy

on:
  workflow_call:
    inputs:
      artifact:
        description: 'The artifact to deploy'
        type: string
        required: true
    outputs:
      status:
        description: 'The status of the deployment'
        type: string
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    outputs:
      status: ${{ steps.set-status.outputs.status }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: List files
        run: ls -l
      - name: Output information
        run: echo "Deploying to production"
      - name: Set status
        id: set-status
        run: echo "status=success" >> $GITHUB_OUTPUT
