name: Reusable Deploy

on:
  workflow_call:
    inputs:
      artifact:
        description: 'The artifact to deploy'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: List files
        run: ls -l
      - name: Output information
        run: echo "Deploying to production"
